### ISSUE TITLE
add 'checkboxes' to a view's custom fields options

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#101]
when you add a checkbox in a form it should also be added as an option for Custom Fields (view settings) so it can be displayed inside a testimonial

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/79106256-d1f1fa80-7d7a-11ea-9aa7-5c25786ca8c5.png)

Here we need only one display type and 2 new extra options, Checked and Unchecked values. See link or date for example.

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/84143930-14287700-aa60-11ea-8e5b-9c33a9e89a6a.png)

'Checked value' should be the same as 'Label'. If you select 'Custom' the input should maintain the value 'GDPR' but make it editable.

**Comment by cristinnaiulia** [comment]
Fixed functionality of custom field checkbox in ST pro - Single Testimonial Template.

**Comment by giucu91** [comment]
before save :
![image](https://user-images.githubusercontent.com/7580330/84771961-ebb1f700-afe2-11ea-9424-f36634c7f6b1.png)

after save : 
![image](https://user-images.githubusercontent.com/7580330/84771997-f8cee600-afe2-11ea-89cf-0263b478a503.png)

**Comment by Florin415** [comment]
If we delete the custom checkbox, create a new one , when we will go to the form it will still try to find the checkbox we deleted : https://prnt.sc/t0qiw3
