### ISSUE TITLE
Reorganize issue

### ISSUE THREAD

**Issue by cristian-raiber** [MachoThemes/strong-testimonials#105]

**Comment by cristianraiber** [comment]
This should be turned ON by default, the option should be removed from the settings panel and save should be done on re-ordering.

Similar to how Simple Custom Post Order works.

**Comment by andyluak** [comment]
The Reorder Setting is removed from setting .

**Comment by razvanaldea89** [comment]
This needs another test after branch 2.40.1 merge into 2.40.2
