### ISSUE TITLE
Remove 'About page'

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/strong-testimonials#108]
move this page's content into the plugin's FAQ on w[dot]org

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/66110794-2d734c80-e5d0-11e9-9127-9fc9295dbc0e.png)

**Comment by cristianraiber** [comment]
Same for the privacy tab contents; it should be a new entry on the plugin's w[dot]org page.

**Comment by andyluak** [comment]
Moved the contents of about page in readme . The privacy part of the about page is already posted on w[dot]org .

**Comment by razvanaldea89** [comment]
Seems to be ok
