### ISSUE TITLE
Nofollow links, noopener noreferrer

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/strong-testimonials#109]
![image](https://user-images.githubusercontent.com/7841556/66110893-61e70880-e5d0-11e9-8152-feb9e6559b0f.png)

**Comment by cristianraiber** [comment]
- Nofollow should be ON by default
- There should be an option to open links in new tab by default and have the `rel="nopener noreferr"` added to those links as well. Read more about it here: https://stackoverflow.com/a/50779400

**Comment by tybylyk** [comment]
On the pages "All testimonials" and "Add New" at the Client Details section on the right side of the Company Website there is the nofollow relationship and selector. But that should be there only if the No Follow option in Settings is Activated. Now is Activated by default, but if you deactivated in Settings shouldn't be also deactivated in the Client Details section?

**Comment by giucu91** [comment]
Update to 2.41.0

![image](https://user-images.githubusercontent.com/7580330/83632039-35dcb680-a5a7-11ea-96c1-34badf41c780.png)

Before update : 
![image](https://user-images.githubusercontent.com/7580330/83632119-5e64b080-a5a7-11ea-9a6f-a2de30225eef.png)

This setting should be like it was before the update.
