### ISSUE TITLE
When re-ordering is set to ON, we should automatically set the menu order in the view

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/strong-testimonials#116]
![image](https://user-images.githubusercontent.com/7841556/66112988-8ba22e80-e5d4-11e9-9ca5-3bfd5f72a30f.png)

**Comment by cristianraiber** [comment]
I also think shouldn't even be an option that users can toggle ON/OFF. I think this should be ON by default and toggle-able to OFF by using a filter. 

cc @giucu91 @razvanaldea89 @andrei-l-cristea @alexjpanagis

**Comment by giucu91** [comment]
@cristian-raiber drag and drop reordering is on, I'll close this ticket.
