### ISSUE TITLE
Ratings on testimonial_average_rating

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/strong-testimonials#120]
https://github.com/MachoThemes/strong-testimonials/blob/a807526dff5326576b6aa16aa83531c39b69581c/includes/class-strong-testimonials-shortcode-average.php#L292

We need to change double with round.

**Comment by bluemorbo** [comment]
A trivial change, but I'm happy to do this if you like :)

**Comment by andyluak** [comment]
Checked the submit by Razvan and it works
