### ISSUE TITLE
review markup fields not working

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#121]
when you set up the schema settings in review markup fields, https://gyazo.com/e41d43accd2fd71850ad21b9516e127e they will not show on the front-end

**Comment by razvanaldea89** [comment]
Can't replicate, they are shown in  `JSON-LD*` format ( recommended by google -> https://developers.google.com/search/docs/guides/intro-structured-data )

**Comment by andyluak** [comment]
The schema is shows in JSON-LD format and works properly .
