### ISSUE TITLE
 Data storage

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#124]
I find it extremely useful when the data is stored in its own tables rather than in posts and postmeta. I noticed that Strong Testimonials is also using posts and postmeta for storing the testimonials. Do you consider to change this? It would help to structure wordpress installations better and to make it easier to clean-up data.

**Comment by giucu91** [comment]
Here we will add an uninstall function like in Modula to delete all our plugin information on deactivation.

**Comment by andyluak** [comment]
Uninstall Functionality works well with no errors found .
