### ISSUE TITLE
Make sure all CSS classes used have a unique prefix

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/strong-testimonials#130]
Related ticket: https://secure.helpscout.net/conversation/1052483329/23468?folderId=2934189
It looks like we ran into an issue, where the `.default` CSS class is being overwritten by a theme.

**Comment by razvanaldea89** [comment]
Think we should add prefix to testimonials elements classes too ( ex. :  `testimonial-heading`) . Might be conflicts there also.

**Comment by razvanaldea89** [comment]
@andyluak  replace previously put `strong` prefix with `wpmtst` and put prefix `wpmtst` also to testimonials elements.

**Comment by razvanaldea89** [comment]
Seems ok and working
