### ISSUE TITLE
Hide left/right arrows on first/last slides

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/strong-testimonials#14]
- Hide left arrow on first slide
- Hide right arrow on last slide

We should probably look into adding a toggle for "continuous sliding".

**Comment by ruhanikhurana** [comment]
@cristian-e @cristianraiber any idea when this feature  will be enhance on plugin?

**Comment by cristianraiber** [comment]
@ruhanikhurana - should be available in the next plugin update :) It's being worked on.

**Comment by razvanaldea89** [comment]
Tested, works

**Comment by ruhanikhurana** [comment]
@razvanaldea89 how can we use this ?

**Comment by razvanaldea89** [comment]
@ruhanikhurana  will be out in update 2.40.2 . In "Views" on "Slideshow" in "Slideshow" settings there will be a checkbox letting you enable/disable continuous sliding.

**Comment by razvanaldea89** [comment]
Commits : https://github.com/WPChill/strong-testimonials/commit/74b09b2fbc7c47c49374e614b76ef1129feb747a and https://github.com/WPChill/strong-testimonials/commit/b4679f4c39d801b231a4d7ff51ef3880e1b4294a are actually and update/fix for multiple forms in same page
