### ISSUE TITLE
Check FA

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/strong-testimonials#141]
Check if we still use font awesome. IF we still use replace all the icons with svg and delete FA

**Comment by giucu91** [comment]
See https://github.com/MachoThemes/strong-testimonials/tree/dev-fa for removing FA

**Comment by razvanaldea89** [comment]
Forgot to add issue to commit. - part 1 of FontAwesome check - https://github.com/MachoThemes/strong-testimonials/commit/277326f4f256eebdc73c1d95bf7010047a20f89c

**Comment by andyluak** [comment]
All FA icons appear to be replaced with svg .
