### ISSUE TITLE
 Title Showing When Unticked in last update

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#149]
Since upgrading Field> Title isn’t working properly.
Tried on all view types.
ALL have the Field> Title unticked but the title/header is still showing.
Have tried ticking, saving unticking, saving, clearing cache etc. but cannot remove title.

But ticking Title then choosing it to link to client website does work.

ticket: https://wordpress.org/support/topic/title-showing-when-unticked/

**Comment by giucu91** [comment]
This is resolved in 2.40.5
