### ISSUE TITLE
incompatible with Fluida theme

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#15]
https://wordpress.org/themes/fluida/

When the theme is active you cannot see any features for the views:
![view](https://user-images.githubusercontent.com/26008574/51690229-f12f2b80-2000-11e9-9a5b-89d25f833edc.png)

**Comment by CryoutCreations** [comment]
Hi
Turning off the theme's [scripts deferring functionality](https://www.cryoutcreations.eu/docs/themes/options/miscellaneous/#js-defer-loading) will resolve this.
We'll make the necessary correction in the next update to limit the scope of deferring to frontend scripts only.

**Comment by cristianraiber** [comment]
@CryoutCreations - thanks for reaching out and commenting on our ticket. I'll be closing this @bc-bjoern as it doesn't seem to be an issue with our plugin, but rather, with the Fluida theme.

**Comment by bc-bjoern** [comment]
Perfect! Thanks a lot!
