### ISSUE TITLE
issue with pagination

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#152]
the buttons are showing up like this: https://gyazo.com/3d4e85fcc1d6a7471e7eaecdee736231
 I noticed that the circular all-page navigation below the testimonial slider appears with a weird effect. Please see screen shot. On hover, the circle turns black, which is not a color anywhere in my theme (including fonts colors, which are set to a grey).

settings: https://gyazo.com/cb15caa5926d532c5102b4540c67a135

**Comment by mplusb** [comment]
https://secure.helpscout.net/conversation/1140859045/26056?folderId=2934197
and: https://wordpress.org/support/topic/pagination-buttons-images-doesnt-work/

**Comment by andyluak** [comment]
Regarding : "On hover, the circle turns black, which is not a color anywhere in my theme (including fonts colors, which are set to a grey)." .  The pagination button on hover always turned black but we can provide you with custom css to change the color .

**Comment by mplusb** [comment]
still happens: https://wordpress.org/support/topic/pagination-buttons-all-show-a-chevron/

**Comment by Florin415** [comment]
Tested the pagination, the issue still appears : https://prnt.sc/sp95cg

**Comment by giucu91** [comment]
@Florin415 test this with branch master
