### ISSUE TITLE
Images dissapearing in views

### ISSUE THREAD

**Issue by AnaSoliven** [MachoThemes/strong-testimonials#154]
After the recent update, my views have been rendering with the star + left and right scroll missing on the site. It comes back when i roll to a backup that hasn't updated the plugin.

![strong-testimonials-images-disappearing](https://user-images.githubusercontent.com/64060517/79829197-c8553c00-83e5-11ea-8bd9-7fc851f15d3d.png)

**Comment by andyluak** [comment]
Hello @AnaSoliven  , I am trying to replicate the issue but I can't . Would you please provide me with your website url so I can investigate this problem further ? Many thanks

**Comment by AnaSoliven** [comment]
Test.onesaas.com

Thanks,
Ana

**Comment by andyluak** [comment]
@AnaSoliven  Could you tell me where is the bug located because I am unable to find it on the page or if you could create a test page for me to access and in there insert there the shortcode for the view so I can have a look and locate the problem . Thanks again

**Comment by AnaSoliven** [comment]
Hi Andy,

Sorry about the late reply. The following URL has the missing images on the
review slider - stars and the left and right scroll on the sides.

http://test.onesaas.com/integrate/quickbooks-online-shopify

I'm using chrome to test this.

Thanks,

*Ana Soliven* / Marketing & Analytics

www.onesaas.com / ana@onesaas.com

When your business apps get along, everyone’s happy.

**Comment by AnaSoliven** [comment]
Weird, after a restart I can see the images. It could have been a cache
issue?

Thanks,

*Ana Soliven* / Marketing & Analytics

www.onesaas.com / ana@onesaas.com

When your business apps get along, everyone’s happy.

**Comment by andyluak** [comment]
I am happy to hear it works now @AnaSoliven  . I was just about to tell you that I can see the icons . I'm happy that everything works fine now and if you encounter other problems , feel free and open a issue and we will get it sorted .
