### ISSUE TITLE
 wpmtst_fields Table in Database – Set to Autload

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#156]
This table in the database is set to autoload, so it’s contributing substantially to the database autload size every time a page is loaded. Is this necessary? I changed autoload to “no” and it doesn’t seem to have caused an issue.

Also, it’s worth mentioning many other database tables related to this plugin are among the top 30 or so largest entries that are set to “autload” in my wp_options table. I assume none of these need to be autoloaded on every page load?

wpmtst_base_forms
wpmtst_view_default

https://wordpress.org/support/topic/wpmtst_fields-table-in-database-set-to-autload/

**Comment by giucu91** [comment]
Also this should be done for : 
- https://github.com/MachoThemes/strong-testimonials/blob/2.41.0/admin/admin-notices.php#L135
- https://github.com/MachoThemes/strong-testimonials/blob/2.41.0/admin/admin-notices.php#L149
- https://github.com/MachoThemes/strong-testimonials/blob/2.41.0/admin/admin-notices.php#L172

- https://github.com/MachoThemes/strong-testimonials/blob/2.41.0/admin/compat.php#L87

-https://github.com/MachoThemes/strong-testimonials/blob/2.41.0/admin/compat.php#L112

- https://github.com/MachoThemes/strong-testimonials/blob/2.41.0/includes/functions-activation.php#L39

- https://github.com/MachoThemes/strong-testimonials/blob/9c7eb53029b6e81ebb855d2d7e3ef288fe9ada92/admin/admin.php#L196
- https://github.com/MachoThemes/strong-testimonials/blob/9c7eb53029b6e81ebb855d2d7e3ef288fe9ada92/admin/admin.php#L211
