### ISSUE TITLE
Handle multiple ratings

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/strong-testimonials#159]
![image](https://user-images.githubusercontent.com/7580330/82037679-2571a400-96ab-11ea-87bd-43c75366a3e8.png)

**Comment by noabnext** [comment]
Hi, I'm the guy that sent this one in. 

I would not call this enhancement, but a **bug**. The feature is already there (multiple fields with star rating and an average shortcode),it just isn't working as it is presented. So I think the label 'bug' or a 'we forgot a little something' would be better. Is it possible to change the label please?

**Comment by cristianraiber** [comment]
@noabnext - it's labelled as "enhancement" as that's what this actually is. A quality of life improvement :) 

P.S: Thanks a bunch for sending this in.

**Comment by mplusb** [comment]
for some reason this does not appear to work at the moment. Needs checking please. Will reopen it for the time being.

**Comment by beatricelucaci** [comment]
+1 I have multiple star ratings in a testimonial and I'm using this shortcode inside the testimonials: [testimonial_average_rating field="all" /]
Each testimonial has different star ratings but for some reason the average rating is the same for all of them when it should be different

**Comment by andrei-l-cristea** [comment]
The shortcode itself works correctly—this was a misunderstanding of what it does. If we have 3 testimonials on a page, each with 3 ratings, the shortcode calculates the average of all 9 ratings. It’s not meant to be placed inside a single testimonial to show the average for just that one.
