### ISSUE TITLE
 new testimonial email displayed in html source issue

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#162]
When receiving a new testimonial by email, the message is displayed as html source, with no graphic layout at all. That seems like a double-encoding problem somewhere. How/where to fix this? I have no such issue with any other admin emails I receive from WP/WC.

This issue seems to come from a hard-coded setting in ST.

strong-testimonials\includes\class-strong-form.php line 506:

$headers = 'Content-Type: text/plain; charset="' . get_option( 'blog_charset' ) . '"' . "\n";

needs to be changed to:

$headers = 'Content-Type: text/html; charset="' . get_option( 'blog_charset' ) . '"' . "\n";

**Comment by cristinnaiulia** [comment]
I cannot replicate this bug.

**Comment by mplusb** [comment]
Web page -like emails should have a header set like Content-Type: text/html to get displayed correctly in the email client (e.g. Thunderbird). As is now, Content-Type: text/plain doesn’t instruct the email client how to properly render the email, and displays it in HTML source instead. That becomes an issue with WooCommerce and/or an email template system
