### ISSUE TITLE
Missing style/script in class-strong-view-slideshow.php: animate.min.css/readmore.js

### ISSUE THREAD

**Issue by ca-evan** [MachoThemes/strong-testimonials#166]
It seems `class-strong-view-slideshow.php` is not including two resources it needs: `animate.min.js` and `readmore.js`

Appending the following to `class-strong-view-slideshow.php` on line 304 seems to fix this.
```php
WPMST()->render->add_script( 'wpmtst-readmore' );
WPMST()->render->add_style( "wpmtst-animate" );
```

Because these resources are not included the `Read more` text on the slideshow view does nothing.

**Expected behavior**
`Read more`  on slideshow view shows more of testimonial text.

#### Used versions
* WordPress version: 5.4.2
* Strong Testimonials version: 2.40.7

**Comment by Florin415** [comment]
Just installed a new local with just Strong Testimonials version 2.40.7 and it seems to work : https://www.screencast.com/t/cAUSvcoVPZ7V .  Can you give us more details regarding this please? Do you have any other plugins installed ?

**Comment by giucu91** [comment]
I'll close this.
