### ISSUE TITLE
cannot activate Strong Testimonials Pro from the extensions page

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#176]
**Describe the bug**
cannot activate Strong Testimonials Pro from the extensions page - it keeps loading without anything happening.
Others seem to work fine

**To Reproduce**
Go to 'Testimonials > Extensions > try to install and activate Strong testimonials Pro'
It will keep loading forever. If you refresh the page it will then show 'Activate' because it installs the plugin, but it does not activate it.
You can activate it from the Plugins page, but on the Extensions page it will still show 'Activate'. Screenshots below.
**Expected behavior**
It should install and activate the plugin.

**Screenshots**
https://gyazo.com/e153a646112bd41a409d4ff24296d9e4
https://gyazo.com/4dc25150dd467d68f522bcab0a326db0

* Which addons do you have installed: 
- [x ] Assignment
- [x ] Advanced Views
- [ x] Pro Templates

#### Used versions
* Strong Testimonials version: 2.50.0

**Comment by cristinnaiulia** [comment]
https://github.com/MachoThemes/strong-testimonials-pro/commit/28ae53b2570f27a889e76b60ad2f5def81452b01
