### ISSUE TITLE
Drag and drop Testimonial not working 

### ISSUE THREAD

**Issue by ViSi19** [MachoThemes/strong-testimonials#181]
**Describe the bug**
Drag and drop not save 
https://drive.google.com/file/d/1aEcL5oplo9Ne412vhhb7CDhxFtLxWkVR/view

**Comment by Florin415** [comment]
Dublura la : https://github.com/MachoThemes/strong-testimonials/issues/175 , si functioneaza cu ultima versiune de ST : https://drive.google.com/file/d/1t9cUjZ6f1BEHw8erVHneEc4ccIvgCMnQ/view . @giucu91 poate fi inchis asta si 175 ?
