### ISSUE TITLE
WP 5.5

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/strong-testimonials#182]
**Describe the bug**
Deprecated: wp_make_content_images_responsive is deprecated since version 5.5.0! Use wp_filter_content_tags() instead. in /home/radianc1/public_html/wp-includes/functions.php on line 4773

**To Reproduce**
Update to WP 5.5

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.5
* Strong Testimonials version: 
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by cristinnaiulia** [comment]
https://github.com/MachoThemes/strong-testimonials/commit/c283929112a1f1555ae9a76eaf0c18b71f2b0800
