### ISSUE TITLE
Expand content in place not working in sidebar

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#183]
**Describe the bug**
If you use the widget: Strong Testimonial View to display testimonials in a sidebar the 'expand content in place' option will not work.

**To Reproduce**
1. View settings: 
![Screenshot_2020-08-17 Views ‹ site title — WordPress(1)](https://user-images.githubusercontent.com/26008574/90397017-e420d400-e09f-11ea-9575-f2e66fd36166.png)

2. Add the widget in a sidebar: https://gyazo.com/6afad79d8b5895cc76f2aa3b831fe0a1

**Expected behavior**
To expand the rest of the testimonial in place

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.5
* Strong Testimonials version: 2.50.0

https://wordpress.org/support/topic/expand-content-in-place-not-working-in-sidebar-only/

**Comment by Florin415** [comment]
On Chrome now the slideshow will start Automatically , but on Mozilla it will not : https://drive.google.com/file/d/1nDMWYQ2g-Zp4COTgsOCtokpzRvsNPfEM/view . The issue is still present.
