### ISSUE TITLE
Multiple slides at a time does not start automatically

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#187]
**Describe the bug**
If you choose to have “multiple slides at a time with these responsive breakpoints:” in Slideshow view, the slideshow doesn’t start automatically if you also have 'Featured Image' checked.
even if the option “Start automatically” is checked.

**To Reproduce**
Screenshot with the settings you need to reproduce this:
![c6fdc0fbcbbc6d8994c2c1c2a57ce6fd](https://user-images.githubusercontent.com/26008574/91161679-bb1dc600-e6d3-11ea-8af9-6c579050b937.png)
If you uncheck the 'Featured image' option it will start

**Expected behavior**
the slideshow should start automatically if that option is selected

Checked on:
- [x] Chrome
- [x] Firefox - user are saying only Firefox, but I was able to see it on Chrome as well.

#### Used versions
* WordPress version: 5.5
* Strong Testimonials version: Version 2.50.2

https://wordpress.org/support/topic/multiple-slides-at-a-time-does-not-start-automatically/
https://wordpress.org/support/topic/slide-show-is-not-starting-with-featured-image/

**Comment by Florin415** [comment]
On Chrome now the slideshow will start Automatically , but on Mozilla it will not : https://drive.google.com/file/d/1nDMWYQ2g-Zp4COTgsOCtokpzRvsNPfEM/view . The issue is still present.
