### ISSUE TITLE
Slideshow view same height slides doesn't work

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/strong-testimonials#188]
**Describe the bug**
If you create a slideshow view with more than 1 testimonial / slide and check the "infinite loop", "Set height to match the tallest slide"  and "Stretch slides" options, only the slides that are direct children to the slider will have same height, the cloned elements will have regular size.

**To Reproduce**
1. Go to Views->Slideshow View
2. Configure settings as in screenshot below

**Expected behavior**
All the slider children, clones also, should have same height

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/91738243-d8153600-ebb8-11ea-900a-5ce19d50dda3.png)

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Strong Testimonials version: 
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by cristinnaiulia** [comment]
https://github.com/MachoThemes/strong-testimonials/commit/c50d708f305ee8dbecfccd94a15e97cc69afd272

**Comment by Florin415** [comment]
Made a slideshow with 4 testimonials with these settings https://prnt.sc/uji7og , but when we use the slider in the testimonials we will have this :   https://drive.google.com/file/d/1OmKb3iOga86KXbFIlGfP-EkArP3PaPf0/view . The issue is not fixed yet.
