### ISSUE TITLE
 Last update breaks testimonial slider on WP 4.9.8

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#28]
https://wordpress.org/support/topic/last-update-breaks-testimonial-slider/

**Comment by giucu91** [comment]
https://wordpress.org/support/topic/testimonials-not-rotating-5/

**Comment by razvanaldea89** [comment]
Tested with WP 4.9.8 and seems to work fine( with branch 2.40.1 ). Think it was fixed.
