### ISSUE TITLE
Issue with single entry views

### ISSUE THREAD

**Issue by knalabs** [MachoThemes/strong-testimonials#35]
I'm facing an issue with testimonial view in specific categories which is having only one testimonial, if we drag and slide it will go on and on. And if I add one more entry in specific category it seems working fine, but what if I'm not having any other testimonials to add.

As this seems pretty clear that if I have misconfigured the view then it should happen with more than one testimonials in the category.

**Comment by giucu91** [comment]
Fixed in 2.37
