### ISSUE TITLE
Display testimonials with minimal stars rating

### ISSUE THREAD

**Issue by aftarfadilah** [MachoThemes/strong-testimonials#45]
I would like to show only above 3 starred testimonials in my front page and show the rest on another page. But I can't find any solutions how. Please add something like a minimum stars number to display like
`[testimonial_view id="2" terms="rating" min="3"]`
or kindly tell me if such functions already exists, thanks.

**Comment by cristian-e** [comment]
Hi.

This can be achieved using the `Advanced Views` extension.
