### ISSUE TITLE
redirect to testimonial page

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#54]
All the testimonials answers are indexed by google.
I want a noindex on there page (example : https://www.lebipolaire.com/temoignage/lenfer/)

The best solution would be that https://www.lebipolaire.com/temoignage/lenfer/ redirect on the testimonial page : https://www.lebipolaire.com/depakote-divalproate-de-sodium-avis-patients-bipolaires/

**Comment by giucu91** [comment]
Add an option to enable or disable testimonial links.

**Comment by giucu91** [comment]
+2

**Comment by giucu91** [comment]
Also if this is disabled add a custom field that will be an url for testimonial page.

**Comment by razvanaldea89** [comment]
URL for testimonial page can be selected from "Link to" setting in the "Views" section.

**Comment by giucu91** [comment]
Move setting "Disable permalinks for testimonials. Off by default." above "Single Testimonial Slug"
Hide Single Testimonial Slug if enabled "Disable permalinks for testimonials. Off by default."
Hide "Full Testimonial" from VIew / TItle / Link to if enabled "Disable permalinks for testimonials. Off by default."
Change Title from "Disable testimonial permalinks" to "Permalinks"

**Comment by andyluak** [comment]
Tested. No errors .
