### ISSUE TITLE
 Latest reCaptcha plugin not displaying anymore in review forms

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#72]
After the latest update (v1.44) of Google Captcha by BestWebSoft (free), reCAPTCHA V2 isn’t displaying anymore in my review forms (popup). It still displays in the wp-login/wp-signup pages though. Rolling back to 1.43 fixes the issue.

**Comment by cristianraiber** [comment]
reCaptcha plugins will stop being supported in ST free. We'll build our PRO implementation for this. 

Managing 3rd party integrations is very time/resource consuming and is also prone to failure. Not the experience we would like our users to have.
