### ISSUE TITLE
SEO unfriendly pagination

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#73]
There is still another thing I wished the plugin could solve... its the absolute SEO unfriendly pagination :(

the pagination starts with page 1 of course. BUT if there are more reviews generated it is shifting the old reviews to page 2 instead of keeping the same URL for the same reviews... and if there are constantly reviews submitted this means each review is on a constantly changing page number over time and google is not able to index all the reviews!! This is a worst case scenario from a SEO perspective.

The pagination should work vice versa, meaning the first (and oldest) reviews should always stay on page number 1 and the new reviews should then be listed on page 2,... page 3... and so on. So the newest review always has to be listed on the highest page number. This is the only way, all the reviews are found on a static URL and can be indexed by google.

**Comment by giucu91** [comment]
We have this. Go to viws and on order select older first.
