### ISSUE TITLE
check the plugin for ADA compliance

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#77]
We are using this plugin on our WordPress site as it's wonderful to use and implement but after checking the site for ADA compliance it's giving the following error on navigation arrows as href attribute doesn't contain any link. (First 2 Empty Link Errors are related to this)

Error:
"If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users."

Reference Link:
http://wave.webaim.org/report#/mmment.com

**Comment by mplusb** [comment]
ADA Accessibility – Thumbnail Alt tag
a way to add alt tags to the thumbnail images
https://wordpress.org/support/topic/ada-accessibility-thumbnail-alt-tag/

**Comment by cristinnaiulia** [comment]
You can add alt tags to thumbnail images from media library. It works for testimonial's feature images too.
