### ISSUE TITLE
automatic excerpt does not work correctly with theme Salient

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#85]

**Comment by graf1x** [comment]
Any news on this getting resolved?

**Comment by razvanaldea89** [comment]
Seems like there is a problem with the number of words set in the view settings. It is overwritten by the theme to 30 words by default.

**Comment by cristianraiber** [comment]
@razvanaldea89 - can you push out a fix? I think we could bump up the filter priority so us hooking on the excerpt_length happens last

**Comment by razvanaldea89** [comment]
@cristianraiber Yup, on it.

**Comment by andyluak** [comment]
This fix will override the exceprt from Salient theme .

**Comment by graf1x** [comment]
> This fix will override the exceprt from Salient theme .

The issue with Salient has not been fixed. If I select automatic excerpt it's blank, if I select manual it displays the custom length excerpt from the content as well as the text from excerpt box.

**Comment by cristianraiber** [comment]
@graf1x - have you downloaded & tested this with our development version or with the w[dot]org version?

We haven't yet released the fix to the public.

**Comment by graf1x** [comment]
> @graf1x - have you downloaded & tested this with our development version or with the w[dot]org version?
> 
> We haven't yet released the fix to the public.

Thanks for your reply. I've only tried the w[dot]org version. It wasn't clear that the fix was only in development. When is it expected to be released to the public?

**Comment by cristianraiber** [comment]
@graf1x - End of January we'll have a release that has more than this fix :)
